apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ .Values.app.name }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Values.app.name }}
          servicePort: {{ .Values.service.port }}
